### ISSUE TITLE
Data register bits overwritten in spi.c

### ISSUE THREAD

**Issue by ThomasEgi** [asif-mahmud/MIFARE-RFID-with-AVR#1]
In the spi.c output/input direction of pins is set with an = on the DDR. It does overwrite any previous bits set by the user causing unintended behavior.

The fix is to |= the bits to set and &= ~ the bits to clear in the AVR usual way.

**Comment by asif-mahmud** [comment]
Thank you so much for noticing that. Updated the spi.c.

**Comment by asif-mahmud** [comment]
let me know if you find anything else.
